### PR TITLE
Added fflush() after each fwrite()

### PR DESCRIPTION
**Pull request by dulldusk**
We could also use the read object to ensure the new content was written.
https://www.aldeid.com/wiki/Secure-delete-files

### CODE REVIEW

**Comment by DanielRuf** [comment]
Hi,

thanks for your PR.

> We could also use the read object to ensure the new content was written.
This would slow it down and is not what it should do.
There are unit tests and file checks to do this (is_readbale).

Not sure if we really have to flush and force write the data as this should be hanled by the PHP internals.

https://stackoverflow.com/a/39407561/753676

It might be only relevant for the algorithms later.

Please drop the commit from master and create a new (feature) branch.

**Comment by dulldusk** [comment]
Hi Daniel. 
I read the post you shared from stackoverflow. It says that if you want to ensure the write at that time (like for logging to be avaivable  instantaneously on file) it is good to do fflush after each fwrite.
For streams, we can even set the read/write buffer to zero, so php does not delay. But for files, as we are trying efectivery write the content each pass, i think it´s very necessary to fflush. If the buffering from php is really inteligent, it could notice that we are overwritting the same position, and at the end of the interaction loop, do only one write at that position, with the last value. This could be checked with some tests, but even if its working now, a future version from php could take this in account, and the shred would stop working. Maybe fflush will drop the performance, but surelly makes the shred more reliable. When i got some time to spare, i will test all this. Be sure i will let you know the results.

**Comment by dulldusk** [comment]
And just to let you know, i created a function formy php file manager, based on your code.
https://github.com/dulldusk/phpfm
I will be working on it from now on.

function php_shred($filepath,$delete=true) {
    // Based on https://github.com/DanielRuf/secure-shred (MIT license)
    // https://www.aldeid.com/wiki/Secure-delete-files
    try {
        // clear stat cache to avoid falsely reported file status
        // use $filepath parameter to possibly improve performance
        clearstatcache(true, $filepath);
        if (is_file($filepath) && is_readable($filepath) && is_writable($filepath)) {
            $read = new \SplFileObject($filepath, 'r');
            $write = new \SplFileObject($filepath, 'r+');
            while (!$read->eof()) {
                $line_pos = $read->ftell();
                $line_content = $read->fgets();
                $line_length = strlen($line_content);
                if ($line_length === 0) continue;
                for ($n=0;$n<3;$n++) { // does 3 overwrites per line
                    $write->fseek($line_pos);
                    $write->fwrite(random_bytes($line_length));
                    $write->fflush();
                }
            }
            if ($delete) $write->ftruncate(0);
            $read = $write = null;
            if ($delete) return unlink($filepath);
            return true;
        }
    } catch(\Exception $e) {
        echo ($e->getMessage().' ('.$e->getCode().')');
    }
    return false;
}

**Comment by DanielRuf** [comment]
> Please drop the commit from master and create a new (feature) branch.

=)

**Comment by DanielRuf** [comment]
It seems it is actually faster with `fflush` so I think it is ok.

See the results of https://travis-ci.com/DanielRuf/php-flush-benchmark/builds/102452138

**Comment by DanielRuf** [comment]
If you need any assistance with creating a clean feature branch, just let me know.

**Comment by DanielRuf** [comment]
Maybe the flushing should be optin. Or the other way (optout).
At least it should be configurable with a setting.

**Comment by DanielRuf** [comment]
Hi @dulldusk,

are you still interested to add this change but as opt-in solution with the needed documentation, tests and examples?

**Pull request closed without merging**
